# Generated by Django 5.2.3 on 2025-06-30 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['code'],
                'unique_together': {('code', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='UploadedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/')),
                ('title', models.TextField(default='Untitled Material')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('flashcards', models.JSONField(blank=True, null=True)),
                ('quiz', models.JSONField(blank=True, null=True)),
                ('mindmap', models.JSONField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
            ],
            options={
                'verbose_name': 'Uploaded Material',
                'verbose_name_plural': 'Uploaded Materials',
                'ordering': ['classroom', 'uploaded_at'],
                'get_latest_by': 'uploaded_at',
            },
        ),
        migrations.CreateModel(
            name='ClassroomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom Membership',
                'verbose_name_plural': 'Classroom Memberships',
                'ordering': ['student', 'classroom'],
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
