# Generated by Django 5.2.3 on 2025-06-24 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmaterial',
            name='cleaned_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmaterial',
            name='flashcards',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmaterial',
            name='quiz',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmaterial',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmaterial',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
