# Generated by Django 5.2.3 on 2025-06-25 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_uploadedmaterial_cleaned_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['code'], 'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='classroommembership',
            options={'ordering': ['student', 'classroom'], 'verbose_name': 'Classroom Membership', 'verbose_name_plural': 'Classroom Memberships'},
        ),
        migrations.AlterModelOptions(
            name='uploadedmaterial',
            options={'get_latest_by': 'uploaded_at', 'ordering': ['classroom', 'uploaded_at'], 'verbose_name': 'Uploaded Material', 'verbose_name_plural': 'Uploaded Materials'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('code', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='classroommembership',
            unique_together={('student', 'classroom')},
        ),
    ]
