# Generated by Django 5.2.3 on 2025-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmaterial',
            name='mindmap',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
